# Generated by Django 6.0.5 on 2026-05-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cue_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='cumple_requisito',
            new_name='cumple_asistencia',
        ),
    ]
