# Generated by Django 6.0.5 on 2026-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
