# Generated by Django 6.0.5 on 2026-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='creado_por_escuela',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escuela',
            name='asistencia_completada',
            field=models.BooleanField(default=False),
        ),
    ]
