# Generated by Django 5.2.6 on 2026-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='editado_por_escuela',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
